env:
  - ZEND_VERSION=2.0.19
install:
  - chmod +x ./scripts/install.sh && source ./scripts/install.sh
  - chmod +x ./scripts/setup-env.sh && source ./scripts/setup-env.sh
script: chmod +x ./scripts/build.sh && ./scripts/build.sh
before_deploy:
  - git config --local user.name $GITHUB_USERNAME
  - git config --local user.email $GITHUB_EMAIL
  - if [[ -z $TRAVIS_TAG ]]; then export TRAVIS_TAG=$TRAVIS_BRANCH; fi
deploy:
  provider: releases
  api_key: $GITHUB_AUTH
  file_glob: true
  file: ./releases/*
  skip_cleanup: true
  overwrite: true
  draft: true
  name: $READABLE_NAME
  on:
    all_branches: true
jobs:
  include:
    - stage: "Builds and Deploy"
      os: osx
      osx_image: xcode9.4
      language: java
    -
      os: linux
      dist: bionic
      sudo: required
      language: generic
    -
      os: windows
      language: shell
      before_install:
        - powershell Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine
        - powershell Install-WindowsFeature Net-Framework-Core
        - cinst -y wixtoolset
